version: '2'

services:
  postdb:
    image: postgres:alpine
    container_name: "postdb"
    environment: 
      POSTGRES_PASSWORD: "mysecretpassword"
      OWNCLOUD_PASSWORD: "mysecretpassword"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    networks:
      - owncloud
  owncloud:
    build: 
      context: ./owncloud
      args:
        OWNCLOUD_VERSION: 10.0.2
    container_name: "owncloud"    
    ports:
      - "81:80"
    links:
      - postdb
    volumes:
      - ~/owncloud/data:/var/www/html/data
      - ~/owncloud/config:/var/www/html/config
      - ~/owncloud/apps:/var/www/html/apps
    networks:
      - owncloud

networks:
  owncloud:
    driver: bridge
