version: '2'

services:
  proxy:
    build: nginx/
    container_name: "portainer-proxy"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - portainer
      - owncloud
      - rails
      - elasticsearch
      - logstash
      - kibana
      - plex
    networks:
      - local

  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    restart: always
    networks:
      - local

  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    restart: always
    command: --templates http://templates/templates.json
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

  postdb:
    image: postgres:alpine
    container_name: "postdb"
    restart: always
    environment: 
      POSTGRES_PASSWORD: "mysecretpassword"
      OWNCLOUD_PASSWORD: "mysecretpassword"
      RAILS_PASSWORD: "mysecretpassword"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ~/postgres-data:/var/lib/postgresql/data
    networks:
      - owncloud
      - rails
  owncloud:
    container_name: "owncloud"
    image: owncloud
    restart: always
    links:
      - postdb
    volumes:
      - ~/owncloud:/var/www/html
    networks:
      - owncloud
      - local

  rails:
    build: rails/
    container_name: "rails"
    restart: always
    depends_on:
      - postdb
    links:
      - postdb
    environment:
      CATAN_LEADERBOARDS_DATABASE_PASSWORD: "mysecretpassword"
    networks:
      - rails
      - local

  elasticsearch:
    build: 
      context:  ./elasticsearch
      args:
        ELASTIC_VERSION: 5.3.2
        ES_DOWNLOAD_URL: https://artifacts.elastic.co/downloads/elasticsearch
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - elknet
      - local
  logstash:
    build:
      context: ./logstash
      args:
        ELASTIC_VERSION: 5.3.2
        LOGSTASH_DOWNLOAD_URL: https://artifacts.elastic.co/downloads/logstash/logstash-5.3.2.tar.gz
    container_name: logstash
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - 5044:5044
      - 9600:9600
    networks:
      - elknet
      - local
      
  kibana:
    build:
      context: ./kibana
      args:
        KIBANA_VERSION: 5.3.2
        KIBANA_DOWNLOAD_URL: https://artifacts.elastic.co/downloads/kibana
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    networks:
      - elknet
      - local

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Chile/Continental
      - PLEX_CLAIM=claim-JsUkCCvkrUNJip7EaSxy
      - ADVERTISE_IP=http://192.168.1.1:32400/
      - CHANGE_CONFIG_DIR_OWNERSHIP:false
    hostname: plex.hochfarber.com
    volumes:
      - ~/plex/config:/config
      - ~/plex/transcode:/transcode
      - ~/media:/data
    networks:
      - local

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  local:
    driver: bridge
  rails:
    driver: bridge
  owncloud:
    driver: bridge
  elknet:
    driver: bridge
