version: '2'

services:
  proxy:
    build: nginx/
    container_name: "portainer-proxy"
    ports:
      - "80:80"
    depends_on:
      - portainer
      - owncloud
      - rails
      - elasticsearch
      - logstash
      - kibana
    networks:
      - local

  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    networks:
      - local

  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    command: --templates http://templates/templates.json
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

  watchtower:
    image: centurylink/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postdb:
    image: postgres:alpine
    container_name: "postdb"
    environment: 
      POSTGRES_PASSWORD: "mysecretpassword"
      OWNCLOUD_PASSWORD: "mysecretpassword"
      RAILS_PASSWORD: "mysecretpassword"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - owncloud
      - rails
  owncloud:
    container_name: "owncloud"
    image: owncloud
    links:
      - postdb
    volumes:
      - ./owncloud-data:/var/www/html
    networks:
      - owncloud
      - local

  rails:
    build: rails/
    container_name: "rails"
    depends_on:
      - postdb
    links:
      - postdb
    environment:
      CATAN_LEADERBOARDS_DATABASE_PASSWORD: "mysecretpassword"
    networks:
      - rails
      - local

  elasticsearch:
    build: 
      context:  ./elasticsearch
      args:
        ELASTIC_VERSION: 5.3.2
        ES_DOWNLOAD_URL: https://artifacts.elastic.co/downloads/elasticsearch
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - elknet
      - local
  logstash:
    build:
      context: ./logstash
      args:
        ELASTIC_VERSION: 5.3.2
        LOGSTASH_DOWNLOAD_URL: https://artifacts.elastic.co/downloads/logstash/logstash-5.3.2.tar.gz
    networks:
      - elknet
      - local
      
  kibana:
    build:
      context: ./kibana
      args:
        KIBANA_VERSION: 5.3.2
        KIBANA_DOWNLOAD_URL: https://artifacts.elastic.co/downloads/kibana
    networks:
      - elknet
      - local

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  local:
    driver: bridge
  rails:
    driver: bridge
  owncloud:
    driver: bridge
  elknet:
    driver: bridge
